project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Statistical Concepts"
  chapters:
    - index.qmd
    - notationguide.qmd
    - listofsymbols.qmd
    - part: "1. Probability"
      chapters:
        - sets.qmd
        - combinatorics.qmd
        - probability.qmd
        - probabilityinr.qmd
        - probabilityexercises.qmd
    - part: "2. Random variables"
      chapters:
        - distributions.qmd
        - expectation.qmd
        - variance.qmd
        - binomial.qmd
        - geometric.qmd
        - normal.qmd
        - uniform.qmd
        - poisson.qmd
        - exponential.qmd
        - rvsinr.qmd
        - rvexercises.qmd
    - part: "3. Working with random variables"
      chapters:
        - rulesforrvs.qmd
        - covariancecorrelation.qmd
        - simulatingrvs.qmd
        - morervsinr.qmd
        - morervsexercises.qmd
    - part: "4. Learning from a sample"
      chapters:
        - descriptivestats.qmd
        - estimation.qmd
        - hypothesistests.qmd
        - limittheorems.qmd
        - ttests.qmd
        - confidenceintervals.qmd
        - samplesinr.qmd
        - sampleexercises.qmd
    - part: "5. Bivariate relationships"
      chapters:
        - dependency.qmd
        - contingencytables.qmd
        - simpleregression.qmd
        - bivariateinr.qmd
        - bivariateexercises.qmd

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    code-copy: true
    code-overflow: wrap
    page-layout: full
    smooth-scroll: true
    code-annotations: hover