# Introduction {#sec-intro .unnumbered}

Hello! I'm Jonathan, and I want to teach you statistics. Specifically, I hope to teach you in two ten-week courses, *Statistical Models for Data Science* and *Time Series Analysis and Forecasting*.

However, not every student arrives at these courses equally well-prepared. Some students have taken multiple college-level statistics courses, others may have not taken any, or last studied these topics ten or twenty years ago. All of these students can succeed, but some of them will succeed more easily with a little review of basic statistical concepts. This mini-course should help lay the foundations for future graduate-level studies in statistical inference.

## How to use this website {#sec-howtouse}

The left-side chapter headings and search bar will help you to select different pages. The right-side table of contents will help you to navigate within each page.

## Purpose and scope

Eleventy years ago, I studied probability and statistics “for statisticians”. Probability theory is elegant and contemplative. Graduate-level work can be completed with just pencil and paper, through proofs and symbolic notation.

The tools and methods discussed in these notes were built from such theoretical work. However, the students I teach are headed (generally) to industry, not to research positions or Ph.D programs. They may never need to author a proof, but they will need to draw conclusions about the world from noisy, biased, incomplete, or insufficient data, to perform their analyses within a modern day tech stack, and to communciate their findings to decisionmakers.

So I want to teach probability and statistics "for data scientists". Data science is a tradecraft, not a body of theory, and it allows people and organizations to answer questions, solve problems, and achieve goals. Data science which does not help us to confront real problems or understand real datasets is not truly data science after all.

The course is split into five modules, which might each correspond to a week's lesson in a formal classroom setting:

 1.  We will start with the basics of probability, including some elements of set theory and combinatorics, which help to motivate and precisely define probability.
 
 2. Then we consider distributions of random variables, which take on different values with different probabilities.
 
 3. Next we dive more deeply into properties and functions of these random variables, including simulation exercises.
 
 4. From there we move to samples of data. We can summarize these samples with descriptive statistics, and learn about theoretical distributions which generated the sample with inferential statistics.
 
 5. Finally, we will discuss relationships between two or more variables, up to and including simple "least squares" regression.
 
An optional series of videos, accessible through [CANVAS TITLE AND HTML LINK] will provide commentary and insight on the reference material found here on the website.

## Recommended textbooks {#sec-referencetexts}

These notes contain some formal mathematical language, but they purposely avoid the depth and rigor of a true graduate-level statistics textbook. I highly suggest that readers of these notes pair them with one or more proper reference tomes. Two recommendations follow:

-   *Introduction to Probability 2nd edition*, by Joseph Blitzstein and Jessica Hwang

    This book is [freely available](http://www.probabilitybook.net) and would help you prepare if you need to spend more time with the foundational topics which precede this course. The authors cover probability and random variables in depth, but they do not cover inference/estimation or regression topics.

-   *Foundations and Applications of Statistics: An Introduction using R* 2nd edition, by Randall Pruim

    This book covers most of our material, but skimps a little on generalized linear models. It focuses mostly on univariate analysis and linear regression, with some basic probability as well as a brief section on logistic regression. It also contains a lot of R code.

## How these notes were made

I assembled these notes using [Quarto](https://quarto.org), a publishing system built around the Pandoc markdown language. I wrote all the code backing these notes in [R](https://cran.r-project.org), and alongside every figure or table you can find the corresponding R code.

Neither the text nor the R code in these notes were generated by AI tools: for better and worse the opinions expressed here are my own, and the I've described these concepts in my own voice.[^index-1] Complaints can be submitted [here](https://chatgpt.com).

[^index-1]: AI assistance was used to draft some of the exercises, and to help with the layout and coding of the website itself.
