# Notation guide

Unfortunately, no two statistical sources use exactly the same notation. Any choice I make will inevitably differ from other sources you consult. I will follow the common conventions when I can, and beg your understanding when I cannot. I will occasionally use two different options to represent the same concept, not because I wish to confuse you, but because sometimes complete consistency creates impossible formatting challenges or even greater ambiguity.

-   Observations from a sample and realizations of a random variable will use lowercase Latin letters, with subscripts as needed:

$$x_1,x_2,...,x_n$$

-   Random variables themselves will use uppercase Latin letters.[^index-2] Subscripts on random variables suggest relations between them, such as two predictors for the same response:

[^index-2]: The most common exception will be my use of the Greek lowercase epsilon $(\varepsilon)$ for an error term, per tradition.

$$Y,Z;\quad X_1,X_2$$

-   True parameters of a model will often use Greek lowercase letters:[^index-3]

[^index-3]: With many exceptions when parameters are traditionally named otherwise, such as using 'a' and 'b' for the parameters of a Uniform distribution or 'df' for degrees of freedom in a *t*-distribution.

$$\mu,\sigma^2,\beta_0,\beta_1$$

-   Estimates of random variables will use a 'hat' accent above the original symbol or use the matching lowercase Latin alphabet letter:[^index-4]

[^index-4]: The hat accent is properly called a circumflex, but statisticians *say* 'hat', *e.g.* the estimate for 'mu' is 'mu-hat'.

$$\hat{\mu},\hat{\beta}_0;\quad s^2,b_1$$

-   Vectors (including univariate samples) will use an arrow accent or boldface lowercase letters. Matrices will use bold uppercase letters (*not* italic):

$$\vec{u},\boldsymbol{y};\quad \mathbf{X}$$

-   Elements of a matrix or data with multiple indices will use a double subscript:

$$\mathbf{X} = \begin{bmatrix} x_{1,1} & x_{1,2} \\ x_{2,1} & x_{2,2} \end{bmatrix};\qquad y_{i \bullet} = \frac{1}{n_i}\sum_j y_{i,j}$$

-   By convention some terms are stylized using blackboard letters, including the set of reals and the set of integers, as well as expectation and variance.

$$\mathbb{R},\mathbb{Z}; \quad \mathbb{V}[X] = \mathbb{E}[X^2] - \mathbb{E}[X]^2$$

-   Script typefaces may be used for other sets, or to "re-use" a letter with more established meanings:

$$\mathcal{S},\mathcal{L},\ell \qquad (\textrm{compare with}\ S, L, l)$$

A further list of all the symbols I use and their meanings can be found in the next section, [List of Symbols](listofsymbols.qmd).